### ISSUE TITLE
Hudson Rock Cybercrime Intelligence Free Integration

### ISSUE THREAD

**Issue by hudsonrock-partnerships** [dmdhrumilmistry/breach-check#8]
Consider adding Hudson Rock's complimentary data to receive additional intelligence about the email address that was compromised in global Infostealer attacks.

Email sample: https://cavalier.hudsonrock.com/api/json/v2/osint-tools/search-by-email?email=manvirdi2000@gmail.com

Free API key and full documentation is available here: https://cavalier.hudsonrock.com/docs

Thank you.

**Comment by hudsonrock-partnerships** [comment]
@dmdhrumilmistry, The rate limit is 50 requests per 10 second

**Comment by dmdhrumilmistry** [comment]
> @dmdhrumilmistry, The rate limit is 50 requests per 10 second

Okay, will integrate it over the weekend
